version: '3.8'
services:
  proxy-service:
    build:
      context: .
      dockerfile: ./apps/proxy-service/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - read-api
      - write-api
    environment:
      - RABBITMQ_URL=amqp://rabbitmq

  read-api:
    build:
      context: .
      dockerfile: ./apps/read-api/Dockerfile
    ports:
      - "3001:3000"
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - redis

  write-api:
    build:
      context: .
      dockerfile: ./apps/write-api/Dockerfile
    ports:
      - "3002:3000"
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_URL=amqp://rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres
    environment:
      PG_PORT: 5434
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123123
    ports:
      - "5432:5432"