version: '3.8'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5673:5672"
      - "15672:15672"

  db:
    image: postgres
    environment:
      PG_PORT: 5434
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123123123
    ports:
      - "5432:5432"

  write-api:
    build:
      context: .
      dockerfile: ./apps/write-api/Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - rabbitmq

  read-api:
    build:
      context: .
      dockerfile: ./apps/read-api/Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - write-api
      - redis
      - db
      - rabbitmq

  proxy-service:
    build:
      context: .
      dockerfile: ./apps/proxy-service/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - read-api
      - write-api
      - rabbitmq
      - db