export enum Patterns {
  READ_USERS = 'READ_USERS',
  READ_POSTS = 'READ_POSTS',
  READ_COMMENTS = 'READ_COMMENTS',

  CREATE_USER = 'CREATE_USER',
  CREATE_POST = 'CREATE_POST',
  CREATE_COMMENTS = 'CREATE_COMMENTS',

  UPDATE_USER = 'UPDATE_USER',
  UPDATE_POST = 'UPDATE_POST',
  UPDATE_COMMENTS = 'UPDATE_COMMENTS',

  CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS',
  CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS',
  CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS',

  UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS',
  UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS',
  UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS',
}
