export enum SocketKeys {
  CREATED_USER = 'CREATED_USER',
  UPDATED_USER = 'UPDATED_USER',

  CREATED_POST = 'CREATED_POST',
  UPDATED_POST = 'UPDATED_POST',

  CREATED_COMMENT = 'CREATED_COMMENT',
  UPDATED_COMMENT = 'UPDATED_COMMENT',
}
